### ISSUE TITLE
Build image error

### ISSUE THREAD

**Issue by AntonZemlya** [khromov/alpine-nginx-php8#6]
Hi! Can you help?

 => ERROR [ 2/14] RUN apk --no-cache add php8=8.0.2-r0     php8-ctype     php8-curl     php8-dom     php8-exif     php8-fileinfo     php8-fpm     php8-gd     php8-iconv     php8-intl    2.5s 
------
 > [ 2/14] RUN apk --no-cache add php8=8.0.2-r0     php8-ctype     php8-curl     php8-dom     php8-exif     php8-fileinfo     php8-fpm     php8-gd     php8-iconv     php8-intl     php8-mbstring     php8-mysqli     php8-opcache     php8-openssl     php8-pecl-imagick     php8-pecl-redis     php8-phar     php8-session     php8-simplexml     php8-soap     php8-xml     php8-xmlreader 
    php8-zip     php8-zlib     php8-pdo     php8-xmlwriter     php8-tokenizer     php8-pdo_mysql     nginx supervisor curl tzdata htop mysql-client dcron:
#6 1.483 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
#6 2.105 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
#6 2.454 ERROR: unable to select packages:
#6 2.487   php8-8.0.8-r0:
#6 2.487     breaks: world[php8=8.0.2-r0]
#6 2.487     satisfies: php8-phar-8.0.8-r0[php8]
------
executor failed running [/bin/sh -c apk --no-cache add php8=${PHP_VERSION}     php8-ctype     php8-curl     php8-dom     php8-exif     php8-fileinfo     php8-fpm     php8-gd     php8-iconv   
  php8-intl     php8-mbstring     php8-mysqli     php8-opcache     php8-openssl     php8-pecl-imagick     php8-pecl-redis     php8-phar     php8-session     php8-simplexml     php8-soap     php8-xml     php8-xmlreader     php8-zip     php8-zlib     php8-pdo     php8-xmlwriter     php8-tokenizer     php8-pdo_mysql     nginx supervisor curl tzdata htop mysql-client dcron]: exit code: 2

**Comment by khromov** [comment]
Hey Anton,

I pushed [a fix](https://github.com/khromov/alpine-nginx-php8/commit/e57bedd9435ebd8983620b2dc532a122a54e18d6) for this problem. I think some fo the extensions are not available for some PHP version causing this issue, but you should be able to build from master now.

Unfortunately I can't update the existing image om Docker Hub right now since they removed automated builds, but you should be able to pull the latest version from `docker.pkg.github.com` as per the readme.
